export const GET_AUTH = 'GET_AUTH';
export const ADD_AUTH = 'ADD_AUTH';
export const REMOVE_AUTH = 'REMOVE_AUTH';

export const GET_PROFILE = 'GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';

export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';

export const REFRESH_SPACES = 'REFRESH_SPACES';

export const REFRESH_ASSETS = 'REFRESH_ASSETS';

export const RELOAD_PROJECTS = 'RELOAD_PROJECTS';

export const RELOAD_DOMAINS = 'RELOAD_DOMAINS';

export const RELOAD_CUSTOM_ENDPOINTS = 'RELOAD_CUSTOM_ENDPOINTS';

export const RELOAD_TEMPLATES = 'RELOAD_TEMPLATES';

export const RELOAD_EMAIL_SERVERS = 'RELOAD_EMAIL_SERVERS';
