const witty = [
    "📚 Knowledge is like dessert—there’s always room for more.",
    "🧠 Brains are muscles too, but they don’t complain after leg day.",
    "✏️ Mistakes are just the tuition fee of wisdom.",
    "📖 Reading is like time travel, but cheaper and without jet lag.",
    "🕵️ Curiosity didn’t kill the cat; it enrolled it in graduate school.",
    "🎩 Education is the art of replacing an empty mind with an open one.",
    "🧩 Every puzzle solved adds another piece to your brain’s wallpaper.",
    "🚀 Learning takes you places—first your desk, then the stars.",
    "🍎 An apple a day keeps ignorance away (if you read while chewing).",
    "🎭 Life imitates art far more than art imitates homework.",
    "💡 Ideas are like lightbulbs—better when switched on.",
    "🎶 Memory is the music of the mind. Just hope it’s not out of tune.",
    "🌍 Geography: proof the world isn’t flat, unless you fold the map.",
    "🔍 Searching for knowledge is the only acceptable form of stalking.",
    "😏 Sarcasm is free, but wisdom is extra credit.",
    "🥇 Every expert was once an amateur… and probably late to class.",
    "🚦 Stop. Think. Then proceed to brilliance.",
    "🍕 Knowledge is like pizza—best shared and always welcome.",
    "🦉 Owls symbolize wisdom because they never have Wi-Fi issues.",
    "🧪 Science: where explosions are encouraged but supervised.",
    "⌛ Time flies. Fortunately, it doesn’t take your homework with it.",
    "🔢 Math: where people buy 60 watermelons and nobody asks why.",
    "🖋 Writing is like magic—you conjure thoughts into existence.",
    "⚡ Learning is shocking only if you lick the socket.",
    "👑 Grammar: it rules you whether you rule it or not.",
    "🌌 Astronomy: teaching us we are small, but still grade-able.",
    "🧊 History repeats itself—first as tragedy, then as homework.",
    "🥽 Science is organized curiosity (with goggles for safety).",
    "📏 Geometry: proving that being well-rounded is a point of pride.",
    "🎨 Art class: where mistakes are masterpieces in disguise.",
    "🥱 Yawning in class burns no calories but signals deep learning.",
    "💻 Coding: turning coffee into algorithms since forever.",
    "🌱 Growth mindset: like gardening, but with less dirt under nails.",
    "🪞 Reflection is the mirror that polishes your mind.",
    "🛠 Learning is the only tool that never rusts.",
    "🛎 Attention: the most expensive currency in any classroom.",
    "🦖 History proves dinosaurs didn’t do their homework.",
    "🎢 Education is the only ride where loops make you smarter.",
    "🎓 A diploma is just a receipt for surviving homework.",
    "🧸 Curiosity is childlike; wisdom is the grown-up sibling.",
    "🐢 Slow learners still win the race—ask any tortoise.",
    "🔥 Ignorance spreads faster than Wi-Fi; learning is the firewall.",
    "🪜 Knowledge: the only ladder you can climb without fear of heights.",
    "🎯 Focus is a superpower disguised as boring concentration.",
    "🌊 Learning: diving into oceans without ever drowning.",
    "🗺 Maps make the world smaller but homework larger.",
    "🛌 Sleep is a lecture you can’t skip—dreams are extra credit.",
    "🍫 Chocolate fuels learning better than any textbook.",
    "🖼 Art: where doodling becomes socially acceptable genius.",
    "🔭 Curiosity doesn’t kill—it telescopes your world.",
    "🪙 Wisdom is the only treasure that multiplies when shared.",
    "🎹 Practice makes perfect… unless it’s bagpipes.",
    "⚖️ Knowledge is weightless but heavy with importance.",
    "🎁 Every new fact is a gift wrapped in curiosity.",
    "🚴 Learning is like riding a bike—except the bike is on fire.",
    "🔔 School bells: the soundtrack of academic suspense.",
    "🦸 Heroes read; villains skip the homework.",
    "🐝 Spelling bees prove that letters can sting.",
    "💭 Daydreaming: the brain’s version of doodling.",
    "🍩 Donuts: circles of happiness, unlike Venn diagrams.",
    "🧙 Magic is just science people forgot to explain.",
    "📬 Reading is opening a letter from the past addressed to you.",
    "🎬 History class: the world’s longest sequel.",
    "🛡 Knowledge is the best armor—lightweight and stylish.",
    "🎉 Learning is the only party where nerds are the DJs.",
    "🪐 Space is cool because homework doesn’t reach there (yet).",
    "🔮 The future belongs to the curious, not the cautious.",
    "📌 Facts stick better than chewing gum under desks.",
    "🚢 History: proof that humans invent mistakes on repeat.",
    "🥕 Carrots help your eyes, but books help your vision.",
    "🎲 Probability: math’s way of flipping coins elegantly.",
    "🐕 Dogs are loyal, but cats know calculus (probably).",
    "🏰 Every book is a castle where your imagination is king.",
    "🖥 Ctrl + Z: life’s most requested button.",
    "⏰ Procrastination: art of waiting until the last second, perfectly.",
    "📦 Knowledge doesn’t take space—but don’t try fitting it in a box.",
    "💎 Every idea starts rough, then polishes into brilliance.",
    "📡 Curiosity is Wi-Fi for the mind.",
    "🎈 Facts are lighter than air, but lift you higher.",
    "🎮 Learning is the ultimate level-up game.",
    "🏖 Vacations end, but knowledge is permanent luggage.",
    "🍄 Curiosity is like a mushroom—strange but nourishing.",
    "🧃 Juice boxes fuel kids; curiosity fuels geniuses.",
    "🪄 Every question is a spell that summons answers.",
    "📂 Knowledge is the only folder that never fills up.",
    "📊 Graphs: because pictures say what numbers sigh about.",
    "🧭 Curiosity is the compass; wisdom is the map.",
    "🎵 Learning is the soundtrack of progress.",
    "📜 History is gossip that survived long enough to be respected.",
    "🧯 Ignorance spreads; education is the fire extinguisher.",
    "🕹 Learning is like a video game—you keep respawning smarter.",
    "🏆 Knowledge is the one prize no one can steal.",
    "🍦 Curiosity melts ignorance faster than ice cream in the sun.",
    "📐 Geometry proves life has too many angles.",
    "💌 Every fact is a love letter to your brain.",
    "🛼 Rolling through lessons is still progress.",
    "🧃 Hydrate your body, educate your mind.",
    "🎭 Every subject is a mask hiding secret treasures.",
    "🚪 Every book is a door disguised as paper.",
    "🧸 Childhood curiosity grows into adult creativity.",
    "📶 Learning boosts your mental signal strength.",
    "🧵 Knowledge threads sew the fabric of wisdom.",
    "🎨 Mistakes are just drafts of masterpieces.",
    "🔒 Education unlocks every door… except the fridge at 3am.",
    "🐇 Curiosity is the rabbit hole—Alice approved.",
    "🥽 Experimenting is curiosity’s way of wearing glasses.",
    "🎤 Words are free; wisdom costs rehearsal.",
    "🛠 Every problem is just a puzzle missing a piece.",
    "🕰 Procrastination is time travel without the fun.",
    "🥂 Here’s to mistakes—our best teachers in disguise.",
    "📺 History: binge-worthy but with fewer cliffhangers.",
    "🦋 Ideas fly when curiosity opens the cage.",
    "🌞 Every sunrise is a free lesson in astronomy.",
    "🧃 Smoothies are blended fruit; wisdom is blended facts.",
    "📔 Notes: tiny treasure maps in messy handwriting.",
    "🪜 Failure is just the first step on the brain’s ladder.",
    "🐙 Curiosity has more arms than any excuse.",
    "🥏 Learning is like a frisbee—catch it or lose it.",
    "🔋 Curiosity charges your brain better than coffee.",
    "🪁 Facts fly higher when tied to questions.",
    "🌵 Curiosity grows even in the driest deserts.",
    "🎯 Every wrong answer points the arrow closer to the bullseye.",
    "🍿 Learning is the only movie that never ends.",
    "🏗 Building knowledge is the best construction project.",
    "🌈 Every subject adds a color to your rainbow.",
    "🧩 Curiosity connects like puzzle pieces.",
    "🦕 Dinosaurs prove that failing biology is not the worst fate.",
    "📎 Curiosity clips ideas together neatly.",
    "🧼 Education washes away ignorance faster than soap.",
    "🧭 A question asked is already half-answered.",
    "🚀 Curiosity fuels rockets and school projects alike.",
    "🍁 Knowledge falls into place like autumn leaves.",
    "🪙 Curiosity pays the highest interest rate.",
    "🎡 Learning is the only ride worth repeating endlessly.",
    "🕊 Wisdom lands gently if you make space for it.",
    "🏰 Castles crumble, but knowledge stays standing.",
    "📤 Curiosity sends questions; learning delivers answers.",
    "📌 Every fact pins ignorance to the board.",
    "🥽 Experimentation is science’s favorite hobby.",
    "🧃 Knowledge quenches curiosity’s thirst.",
    "⚓ Learning anchors you in any storm.",
    "🛹 Every mistake is just practice with better balance.",
    "🕹 Questions are cheat codes for life.",
    "🍋 When life gives you lemons, ask: what’s the pH?",
    "🎭 Curiosity is the actor, learning is the stage.",
    "🧊 Ideas crystallize when you keep asking why.",
    "🎇 Every fact is a spark—collect enough to light fireworks.",
    "🐠 Curiosity swims; ignorance sinks.",
    "📦 Learning unpacks the mystery box of life.",
    "📡 Questions are signals—answers are connections.",
    "🧮 Math counts even when you don’t want it to.",
    "📢 Curiosity whispers, but wisdom echoes.",
    "🌪 Curiosity stirs storms of imagination.",
    "🛶 Learning rows you across ignorance’s river.",
    "🥐 Croissants prove that geometry tastes delicious.",
    "🎀 Knowledge ties the ribbons on curiosity.",
    "🧵 Questions unravel mysteries like sweaters.",
    "🔑 Learning is the skeleton key to every lock.",
    "🍀 Curiosity is luck you create yourself.",
    "🐾 Curiosity leaves footprints everywhere.",
    "🏹 Questions aim; answers land.",
    "🌙 Curiosity dreams under the stars.",
    "🧂 Salt adds flavor; questions add meaning.",
    "🍓 Curiosity grows in every season.",
    "🪞 Knowledge reflects what curiosity seeks.",
    "📍 Questions are the map pins of wisdom.",
    "🎲 Curiosity rolls the dice of discovery.",
    "🎪 Learning is the circus where curiosity performs.",
    "🦜 Parrots repeat; learners understand.",
    "📡 Curiosity is the antenna of the mind.",
    "🧪 Even failed experiments add to wisdom’s recipe.",
    "📚 Books are the Wi-Fi of history.",
    "🧊 Curiosity never freezes—it melts ignorance.",
    "📀 Ideas spin like records—keep playing them.",
    "🎢 Every question is the start of a thrilling ride.",
    "🕰 Patience and curiosity are twins who grow wisdom.",
    "🌻 Curiosity blooms even in cracks of routine.",
    "🧠 Brains love questions more than answers.",
    "🐉 Knowledge slays dragons of doubt.",
    "🌊 Curiosity makes waves, wisdom surfs them.",
    "🦄 Questions are magical, answers believable.",
    "🌋 Curiosity erupts into learning’s lava.",
    "🪁 Knowledge soars when curiosity holds the string.",
    "🛡 Facts are the shield against confusion.",
    "🎺 Questions trumpet the arrival of wisdom.",
    "🧩 Each question adds a missing piece.",
    "🚀 Curiosity launches; learning lands.",
    "🎂 Curiosity is the candle, wisdom the cake.",
    "🐌 Even slow curiosity wins the wisdom race.",
    "🔦 Knowledge is a flashlight for dark corners.",
    "🎇 Every idea is fireworks in disguise.",
    "📌 Questions tack wisdom to memory.",
    "🧸 Curiosity is childhood’s favorite toy.",
    "🍯 Learning sweetens life better than honey.",
    "🔔 Each fact rings louder than ignorance.",
    "🪴 Curiosity grows when watered with patience.",
    "🎨 Questions paint; answers frame.",
    "🌍 Curiosity travels without tickets.",
    "🧊 Every answer cools the heat of confusion.",
    "📡 The mind’s best signal: curiosity.",
    "🧃 Every sip of learning refreshes.",
    "🏗 Questions build; answers decorate.",
    "🎁 Curiosity unwraps life’s best surprises.",
    "🐦 Knowledge takes flight with curiosity’s wings.",
    "🌌 Curiosity is the telescope of the soul.",
    "🧂 A pinch of curiosity flavors every lesson.",
    "🍎 Learning is the crunchiest fruit.",
    "🧭 Curiosity points north, wisdom walks there.",
    "🎯 Questions aim arrows at wisdom’s bullseye.",
    "🪄 Answers sparkle only when curiosity waves the wand.",
    "🌱 Knowledge sprouts from curious soil.",
    "🎶 Questions hum, answers sing.",
    "🦉 Wisdom is curiosity all grown up.",
    "🏔 Curiosity climbs mountains others ignore.",
    "🔮 Every question is a crystal ball.",
    "🧸 Curiosity hugs the unknown tightly.",
    "🎇 Learning lights up like fireworks in the brain."
];


const children = [
    "🐉 Imagine your brain as a dragon — every fact you learn is another shiny gold coin in its treasure hoard!",
    "🍕 Studying is like pizza: better in slices, not all at once.",
    "🦸 Every page you read is like leveling up your superhero powers!",
    "🐌 Slow and steady studying beats racing and forgetting.",
    "🦄 Unicorn fact: naps turn boring facts into magical memories.",
    "🍭 Knowledge is candy — eat it one sweet at a time!",
    "🐒 Teach your notes to a monkey plushie. If it claps, you’re ready.",
    "🚀 Studying = fueling your brain rocket. Blast off soon!",
    "🦕 Dinosaurs remembered things for millions of years. You can handle a test!",
    "🎩 Reading aloud? Pretend you’re a wizard casting a knowledge spell.",
    "🧃 Water is brain juice — sip wisely, young scholar!",
    "🧟 Brains love breaks, or they turn into sleepy zombies.",
    "🍉 Bite-sized study chunks are juicier than giant watermelons of cramming.",
    "🦸 Your pencil is your magic sword. Wield it bravely!",
    "🎮 Testing yourself is like playing a video game on ‘Hard Mode’.",
    "🐱 Cats never cram. They nap, learn, nap again — be like a cat.",
    "🍌 Bananas = study snacks. Monkeys are secretly geniuses.",
    "🐝 Busy bees collect pollen; busy brains collect facts.",
    "🎭 Act out your study notes dramatically. Even Shakespeare would clap.",
    "🛡️ Every small win adds armor to your brain-knight.",
    "🐸 Ribbit! Frogs say: jump over distractions, land on focus.",
    "🍩 Breaks are like donuts — skip too many, and you miss the best part.",
    "🌟 Every question answered is a star in your night sky of knowledge.",
    "🐧 Penguins learn by waddling around together. Study buddies work too!",
    "🎨 Doodle your notes — even stick figures can pass exams.",
    "🦖 Big topics are dinosaurs: break them into smaller dino nuggets.",
    "🍫 Reward yourself with chocolate power-ups after a chapter!",
    "🧚 Pretend each fact is a fairy whispering a secret into your ear.",
    "🦆 Ducks say: quack it out loud to remember better.",
    "🐉 Hard problem? Imagine you’re a knight solving dragon riddles.",
    "🎲 Random quiz yourself — it’s like rolling dice for your brain.",
    "🦋 Small ideas flutter into big butterflies if you let them rest.",
    "🥦 Your brain loves broccoli more than candy… but candy helps too!",
    "🚴 Move around: your brain thinks better on wheels and wiggles.",
    "🦊 Be sly like a fox — trick yourself into revising with games.",
    "🌈 Facts are rainbow colors. Mix them together to make new ideas.",
    "🍿 Popcorn fact: brains love surprise quizzes like kernels popping.",
    "🧟‍♂️ Too much screen time makes zombie-brains. Go outside for XP!",
    "🦙 Llamas never multitask. Be the llama. Focus!",
    "🎤 Pretend you’re giving a concert where the lyrics are your notes.",
    "🐔 Chickens peck one seed at a time. Do the same with your chapters.",
    "🍓 Juicy tip: the brain remembers things better when you chew gum.",
    "🌍 Every fact is a puzzle piece — soon you’ll have the whole world picture!",
    "🐠 Goldfish forget in seconds. You’re better than a goldfish!",
    "🎁 Each study session is a gift to your future self — no wrapping needed.",
    "🦄 Even unicorns have to practice magic — practice your notes too!",
    "🍎 Teachers love apples, but your brain loves apple breaks more.",
    "🛸 Aliens would study Earth facts. Be smarter than the aliens!",
    "🐯 A roaring mind is scarier than any test — keep feeding it facts."
];

const magical = [
    "🪄 Every fact learned is another gem in your wizard’s crown.",
    "📜 Reading notes is like peeking into an ancient scroll of secrets.",
    "🦉 Owls never cram — they study nightly by moonlight.",
    "✨ Each page you turn releases a sparkle of wisdom.",
    "🔮 Quizzing yourself is like gazing into a crystal ball of answers.",
    "🧙 Long study marathons are like spells that fizzle — short bursts work best.",
    "🌌 Knowledge is a starry sky — collect constellations one by one.",
    "🐉 Every solved problem tames another tiny dragon.",
    "🪞 Repeating aloud is casting your memory spell twice.",
    "📖 Review today’s notes or risk them turning into disappearing ink!",
    "🌙 Sleep is your invisibility cloak for forgetting — wear it well.",
    "⚗️ Breaks brew stronger potions of focus.",
    "🕯️ Light your brain like a lantern — one thought at a time.",
    "💫 Spaced repetition is the time-turner of learning.",
    "🧹 A tidy desk is a clear magic circle for study spells.",
    "🪙 Each fact collected is like a shiny coin in your wizard’s pouch.",
    "🐲 Big tasks are dragons — slice them into smaller scales.",
    "🍵 Tea, water, or cocoa are potions to keep your brain awake.",
    "🦄 Magical creatures don’t rush — they master their craft slowly.",
    "📜 Summarizing notes is like writing your own spell scroll.",
    "🔑 Curiosity is the skeleton key to every enchanted door.",
    "🪄 Active recall is your most powerful wand movement.",
    "🌟 Small sparks of effort make blazing bonfires of wisdom.",
    "🧚 Whisper your notes to the air — fairies carry them to memory.",
    "🌌 Each break is like a shooting star: brief but brilliant.",
    "🦉 Teaching others is the owl’s way of proving wisdom.",
    "🔮 Visualizing success is like casting a prophecy for yourself.",
    "🧙 Multitasking is like juggling spells — one is enough, or chaos arrives.",
    "✨ Celebrate every little win with a flicker of fireworks in your mind.",
    "🌿 Plants grow with water, brains with review.",
    "📖 Reading aloud turns words into magic spells.",
    "🪄 Flashcards are enchanted talismans of memory.",
    "🌞 Morning study casts brighter spells than midnight cramming.",
    "🧙‍♀️ Focus is the wizard’s shield against distractions.",
    "🪶 Write notes by hand — quills hold more magic than keyboards.",
    "🧩 Break lessons into puzzle pieces; assemble the spell later.",
    "🎇 New facts shine brighter when linked to old ones.",
    "🐉 Brave the hardest task first — it’s the fiercest dragon.",
    "📜 A lesson reviewed within a day is like a charm that never fades.",
    "🧙 Every mistake is simply a potion recipe that needs tweaking.",
    "🌌 Think of your memory as a spellbook — it must be reread often.",
    "🦋 Take a walk — even butterflies refresh their wings.",
    "🎩 Studying with friends is a wizard council of learning.",
    "🌠 Big ideas fall like meteors when the mind rests.",
    "📚 Organize your notes — scattered scrolls confuse even great wizards.",
    "🧙 Don’t just reread — summon knowledge by testing yourself.",
    "🪞 Reflection after study is a mirror of wisdom.",
    "🔔 Small reminders are like charms tied to your wand.",
    "🐉 Imagine your brain leveling up with every fact — wizard XP!",
    "🌜 Naps are short spells of memory magic.",
    "🧪 Highlight wisely — too much potion spoils the brew.",
    "🎇 Flashcards are fireworks for your brain.",
    "🧭 Clear goals are compasses for magical quests.",
    "🌟 Consistency is the wizard’s staff: sturdy and reliable.",
    "🔮 Preview a topic — like scrying the future of your study session.",
    "🕰️ Pomodoro timers are enchanted hourglasses for focus.",
    "🦄 Connect ideas together — that’s how unicorns are spotted.",
    "🎶 Instrumental music is background magic, not distraction.",
    "🧙 One focused hour beats a week of sloppy spellcasting.",
    "🪄 Memory palaces are castles in your mind — decorate them often.",
    "🌞 Natural light is sunshine magic for your thoughts.",
    "🪶 Rewrite notes in your own style — your personal grimoire.",
    "🧚 Random quizzing is like fairy dust that strengthens spells.",
    "🧙 The wand chooses the wizard; the method chooses the student.",
    "📖 Read once to see the forest, twice to see the trees.",
    "🪄 Practicing problems is summoning spells, not just watching them.",
    "🌌 Your progress grows like galaxies — slow but spectacular.",
    "🐲 Each challenge is a riddle whispered by dragons.",
    "🎭 Act out definitions — wizards love theatrics.",
    "📜 Write your own riddles from your notes to test yourself later.",
    "🪄 Don’t rush — even Merlin studied for years.",
    "🌠 Review sessions are comets — visit them regularly or they vanish.",
    "🧙‍♂️ Self-testing is dueling your past self — win every time.",
    "📖 Skim once like a scout, then study deeply like a wizard.",
    "✨ Visuals are illusions your brain loves to keep.",
    "🧹 Clear distractions like sweeping dust from a magic circle.",
    "🌙 Sleep ties threads of memory into enchanted tapestries.",
    "🧚 Imagine each fact glowing — can you recall the brightest ones?",
    "🐉 Hard questions guard treasure — solve them for golden rewards.",
    "🧭 Stay patient; even wizards don’t learn lightning bolts in a day.",
    "🌞 Start with a warm-up spell — an easy win boosts your magic.",
    "🎇 Every quiz you make is a spell that tests your wizardry.",
    "🧪 Mnemonics are potions bubbling with memory tricks.",
    "🦉 Evening review makes owls proud — wise and ready.",
    "🪄 Small steps daily enchant the path to mastery.",
    "🌌 Connecting facts builds constellations of knowledge.",
    "🧙 Notes rewritten thrice glow like runes in your mind.",
    "📜 Learning is slow alchemy — from lead confusion to golden clarity.",
    "🧚 Tiny rests restore big wings of focus.",
    "🌟 Remember: mistakes are just sparks before the real firework.",
    "🪄 Focus charms protect against sneaky distractions.",
    "🔮 Envision success before you begin — the prophecy helps.",
    "🦄 Magical minds grow from daily spells of practice.",
    "🌠 Each study session adds stars to your wizard’s sky.",
    "🧙 Sleep is the grandmaster’s final spell for memory.",
    "📚 A question asked is a doorway opened in your tower of wisdom.",
    "🧹 Tidy notes = tidy mind. Even wizards dislike messy spellbooks.",
    "🪄 Treat every subject as a kingdom — explore one castle at a time.",
    "🌌 Your brain is a galaxy — fill it with glowing constellations of knowledge."
];


export const loadingMessages = {
    witty, children, magical
}
